const TYPE_ACTIONS = {
    GET_ALL_VISUALIZATIONS: "GET_ALL_VISUALIZATIONS",
    UPDATE_VISUALIZATIONS: "UPDATE_VISUALIZATIONS",
    UPDATE_VISUALIZATION: "UPDATE_VISUALIZATION",
    UPDATE_VISUAL_ARRAY: "UPDATE_VISUAL_ARRAY",
    GET_ALL_DASHBOARDS: "GET_ALL_DASHBOARDS",
    UPDATE_DASHBOARDS: "UPDATE_DASHBOARDS",
    FILTER_DASHBOARDS: "FILTER_DASHBOARDS",
    GET_ALL_QUERIES: "GET_ALL_QUERIES",
    SET_IS_LOADING: "SET_IS_LOADING",
    SET_PROPERTIES: "SET_PROPERTIES",
    UPDATE_QUERIES: "UPDATE_QUERIES",
    UPDATE_QUERIE: "UPDATE_QUERIE",
    SET_PATH: "SET_PATH",
}

export default TYPE_ACTIONS