const TYPE_ACTIONS = {
    UPDATE_VISUALIZATIONS: "UPDATE_VISUALIZATIONS",
    UPDATE_DASHBOARDS: "UPDATE_DASHBOARDS",
    UPDATE_QUERIES: "UPDATE_QUERIES",
    UPDATE_STATE: "UPDATE_STATE",
}

export default TYPE_ACTIONS